DROP TABLE APP_USER_ROLE;

DROP TABLE APP_USER_IN_ROLE;

DROP TABLE APP_USER;

DROP TABLE APP_PREDEFINED_VALUE;

CREATE TABLE APP_PREDEFINED_VALUE (

    TYPE        VARCHAR(31) NOT NULL,

    CODE        VARCHAR(20) NOT NULL,

    FLAG        VARCHAR(20) NULL,

    DESCRIPTION VARCHAR(50) NOT NULL

    );



CREATE TABLE APP_USER (

    USER_ID         INTEGER NOT NULL,

    USERNAME        VARCHAR(50) NOT NULL,

    NAME            VARCHAR(50) NOT NULL,

    PASSWORD        VARCHAR(32) NOT NULL,

    ENABLED         NUMBER(1,0) NOT NULL,

    EMAIL           VARCHAR(50) NOT NULL,

    DOB             DATE NULL,

    VERSION         INTEGER NOT NULL,

    UPDATE_BY       INTEGER NOT NULL,

    DATETIME_UPDATE DATE NOT NULL,

    ADD_BY          INTEGER NOT NULL,

    DATETIME_ADD    DATE NOT NULL

    );



CREATE TABLE APP_USER_IN_ROLE (

    FK_USER_ID      INTEGER NOT NULL,

    FK_USER_ROLE    VARCHAR(50) NOT NULL

    );



CREATE TABLE APP_USER_ROLE (

    ROLE_NAME           VARCHAR(50) NOT NULL,

    STATUS              NUMBER(1,0) NULL,

    ROLE_DESCRIPTION    VARCHAR(100) NOT NULL,

    ROLE_ACTIVITY       VARCHAR(255) NOT NULL,

    VERSION             INTEGER NOT NULL,

    ADD_BY              INTEGER NULL,

    DATETIME_ADD        DATE NULL,

    UPDATE_BY           INTEGER NULL,

    DATETIME_UPDATE     DATE NULL

    );

CREATE SEQUENCE SEQ_APP_USER

    INCREMENT BY 1

    START WITH 1

    NOMAXVALUE

    NOMINVALUE

    NOCYCLE

    CACHE 20

    NOORDER;

INSERT INTO APP_PREDEFINED_VALUE(TYPE, CODE, FLAG, DESCRIPTION)
  VALUES('Role_Activity', 'ACT_USERADM', '1', 'User Admimistrator');

INSERT INTO APP_PREDEFINED_VALUE(TYPE, CODE, FLAG, DESCRIPTION)
  VALUES('Role_Activity', 'ROLE_USER', '0', 'Account');

INSERT INTO APP_USER(USER_ID,USERNAME, ADD_BY, DATETIME_ADD, UPDATE_BY, DATETIME_UPDATE, VERSION, NAME, PASSWORD, ENABLED, EMAIL, DOB)
  VALUES(SEQ_APP_USER.NEXTVAL,'surewin', '1', TO_DATE('2007-07-27 18:30:59','YYYY-MM-DD HH24:MI:SS'), '1', TO_DATE('2007-08-11 12:06:43','YYYY-MM-DD HH24:MI:SS'), 2, 'DTSB', '5f4dcc3b5aa765d61d8327deb882cf99', 1, 'dtsb@yahoo.com', TO_DATE('2007-08-06 00:00:00','YYYY-MM-DD HH24:MI:SS'));

INSERT INTO APP_USER_IN_ROLE(FK_USER_ID, FK_USER_ROLE)
  VALUES(1, 'ADMIN');

INSERT INTO APP_USER_ROLE(ROLE_NAME, ADD_BY, DATETIME_ADD, UPDATE_BY, DATETIME_UPDATE, VERSION, STATUS, ROLE_DESCRIPTION, ROLE_ACTIVITY)
  VALUES('ADMIN', '1', TO_DATE('2007-07-27 18:30:59','YYYY-MM-DD HH24:MI:SS'), 1, TO_DATE('2007-07-27 18:30:59','YYYY-MM-DD HH24:MI:SS'), 1, 1, 'Have all the privilege', 'ROLE_USER;ACT_USERADM');
